/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'on-background': '#e1e2ec',
        'secondary-container': '#00a572',
        'secondary-fixed-dim': '#4edea3',
        'on-primary': '#002e6a',
        'on-secondary-container': '#00311f',
        surface: '#10131a',
        'inverse-surface': '#e1e2ec',
        'secondary-fixed': '#6ffbbe',
        'surface-container-high': '#272a31',
        'error-container': '#93000a',
        'on-primary-fixed': '#001a42',
        'on-error-container': '#ffdad6',
        background: '#10131a',
        'tertiary-container': '#ca8100',
        'on-tertiary-container': '#3e2400',
        'surface-variant': '#32353c',
        'on-primary-container': '#00285d',
        'primary-fixed': '#d8e2ff',
        'primary-container': '#4d8eff',
        'inverse-primary': '#005ac2',
        'inverse-on-surface': '#2e3038',
        primary: '#adc6ff',
        'on-primary-fixed-variant': '#004395',
        'surface-dim': '#10131a',
        tertiary: '#ffb95f',
        'on-surface-variant': '#c2c6d6',
        'on-secondary': '#003824',
        'surface-tint': '#adc6ff',
        error: '#ffb4ab',
        'tertiary-fixed': '#ffddb8',
        'primary-fixed-dim': '#adc6ff',
        'outline-variant': '#424754',
        'on-error': '#690005',
        'surface-container': '#1d2027',
        'surface-container-low': '#191b23',
        'on-tertiary-fixed': '#2a1700',
        outline: '#8c909f',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary': '#472a00',
        secondary: '#4edea3',
        'on-surface': '#e1e2ec',
        'surface-bright': '#363941',
        'surface-container-lowest': '#0b0e15',
        'surface-container-highest': '#32353c',
        'on-tertiary-fixed-variant': '#653e00',

        // Semantic aliases (CSS variables for light/dark)
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-card': 'var(--bg-card)',
        'bg-border': 'var(--bg-border)',
        'bg-hover': 'var(--bg-hover)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'glass-bg': 'var(--glass-bg)',
        'glass-border': 'var(--glass-border)',
        'glass-strong-bg': 'var(--glass-strong-bg)',
        light: {
          primary: '#f6f8fa',
          secondary: '#ffffff',
          card: '#ffffff',
          hover: '#f3f4f6',
          border: '#e2e8f0',
        },
        brand: '#4d8eff',
        'brand-hover': '#adc6ff',
        danger: '#ffb4ab',
        success: '#4edea3',
        warning: '#ffb95f',
        'brand/10': 'rgba(77, 142, 255, 0.1)',
        'success/10': 'rgba(78, 222, 163, 0.1)',
        'danger/10': 'rgba(255, 180, 171, 0.1)',
        'warning/10': 'rgba(255, 185, 95, 0.1)',
        'bg-hover/80': 'rgba(39, 42, 49, 0.8)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        'margin-desktop': '40px',
        xs: '4px',
        xl: '32px',
        'margin-mobile': '16px',
        base: '4px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        caption: ['Inter'],
        'body-lg': ['Inter'],
        'title-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
